### ISSUE TITLE
Atom is disappeared after adding "Unsaturated" checkbox Properties

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1418]
**Steps to Reproduce**
1. Launch the Ketcher
2. Create structure with Atom
3. Double-click on the Atom with Selection Tool
4. Checked the "Unsaturated" Query specific checkbox in the Atom Properties
5. Click on the "OK" button

**Expected behavior**
Atom is shown with "Unsaturated" Query specific properties in the Ketcher editor

**Actual behavior**
Atom is disappeared. The ketcher editor is empty. 

After clicking on any blank region in the Kencher editor -> the Browser Console is displayed the error:
Uncaught Error: Unsaturated atom invalid value
    at main.6f7788c4.js:2:1576120
    at n.value (main.6f7788c4.js:2:1576250)
    at main.6f7788c4.js:2:1633682
    at Map.forEach (<anonymous>)
    at e.value (main.6f7788c4.js:2:1633633)
    at e.value (main.6f7788c4.js:2:1631457)
    at Pi.update (main.6f7788c4.js:2:1640598)
    at e.value (main.6f7788c4.js:2:3390880)
    at e.value (main.6f7788c4.js:2:3346071)
    at n.f (main.6f7788c4.js:2:3388716)

**Screenshots**
![image](https://user-images.githubusercontent.com/103422815/162920013-baaff36f-e8d7-4dd9-8394-d22375c49532.png)

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows]
 - Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit
 - Release 2.5.0

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
Atom is shown with "Unsaturated" Query specific properties in the Ketcher editor after adding "Unsaturated" checkbox Properties.
