### ISSUE TITLE
An error appears in the Console, when collapsing and expanding a screen with a template, that has AP, in Macro

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5540]
**Steps to Reproduce**
1.	Open the Console
2.	Draw any template on the canvas
3.	Switch to the Macro mode and switch to the Micro mode again
4.	Add one attachment point to a template via the Right-click menu  
        
       <img width="117" alt="image" src="https://github.com/user-attachments/assets/0efd325a-de51-42e4-99ed-0fcd39abf849">

5.	Switch to the Macro mode
6.	Collapse and expand a screen     
       
      <img width="95" alt="image" src="https://github.com/user-attachments/assets/9b7911e7-f625-46a4-ac64-6864cc045d3f">

**Actual behavior**
There is an error in the Console: main.571c1a54.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'getVBoxObj' in undefined
    at main.571c1a54.js:2:1435655
    at Array.forEach (<anonymous>)
    at Function.value (main.571c1a54.js:2:1435554)
    at t.value (main.571c1a54.js:2:1590064)
    at t.value (main.571c1a54.js:2:1594415)
    at main.571c1a54.js:2:1650128
    at Array.forEach (<anonymous>)
    at n.value (main.571c1a54.js:2:1650079)
    at n.value (main.571c1a54.js:2:1648807)
    at n.value (main.571c1a54.js:2:1671395)

<img width="215" alt="image" src="https://github.com/user-attachments/assets/1bb1b6ca-a89a-43be-9790-a5c82d202599">

<img width="944" alt="image" src="https://github.com/user-attachments/assets/fdfbd23b-7304-46df-9e07-7c73b7c54d4b">

[rc.test.lifescience.opensource.epam.com-1726656901263.log](https://github.com/user-attachments/files/17045634/rc.test.lifescience.opensource.epam.com-1726656901263.log)

**Expected behavior**
There is no error in the Console

**Screenshots**

https://github.com/user-attachments/assets/c8616332-526b-47f9-82cf-3919ca8b60e9

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (version 22H2) 
 - Browser: Сhrome
 - Version: (128.0.6613.138) x64

**Ketcher version** 2.25.0-rc.2, Build at 2024-09-14; 10:54:23

**Indigo version** 1.24.0-rc.2.0

**Comment by ViktoriaTkacheva** [comment]
Added to Refined Backlog after discussion with Roman Rodionov

**Comment by AlexeyGirin** [comment]
That logic has been removed

- Ketcher Version 3.17.0-rc.1 Build at 2026-06-02; 21:27:10
- Indigo Version 1.45.0-rc.2.0-g168fb85f2-wasm32-wasm-clang-23.0.0
- Chrome Version 148.0.7778.179 (Official Build) (64-bit)
- Win11
